name: platform_device_id_plus_platform_interface
description: A common platform interface for the platform_device_id_plus plugin.
homepage: https://github.com/musthafa1996/platform_device_id_plus/tree/master/platform_device_id_plus_platform_interface
version: 1.0.2

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

