name: platform_device_id_plus_web
description: web implementation of the platform_device_id_plus plugin.
version: 1.0.2
homepage: https://github.com/musthafa1996/platform_device_id_plus/tree/master/platform_device_id_plus_linux

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  platform_device_id_plus_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: platform_device_id_plus
    platforms:
      web:
        pluginClass: PlatformDeviceIdWebPlugin
        fileName: platform_device_id_plus_web.dart
